### ISSUE TITLE
Initialize dataset when creating form

### ISSUE THREAD

**Issue by tadamK** [get-focus/focus-graph#106]
Hello,

@Ephrame as seen together, when I create a form, the dataset is empty.

It bothers me when I save, because the props `saving` never pass to true and I can't use it to do another action.

For the moment, I use this workaround :

```
import {actionBuilder} from 'focus-graph/actions/entity-actions-builder';

const svcCreationWrapper = svc => (id => id ? svc(id) : Promise.resolve({id: null}))

export const actionBuilderRefCustom = args => {
    const customArgs = _.assign({}, args, {service: svcCreationWrapper(args.service)});
    return actionBuilder(customArgs);
}
```

"focus-graph": "3.0.0-rc3".

**Comment by TomGallon** [comment]
Fixed by #131
