### ISSUE TITLE
[selectFor] Error when opening a form in edit mode 

### ISSUE THREAD

**Issue by tadamK** [get-focus/focus-graph#111]
Hello,

When I open a form in edit mode (with toggleEdit(true)) and it contains a selectFor, an error is sent.

It's an old bug, but the issue was never created...

**Comment by TomGallon** [comment]
i do not reproduce it. 
@tadamK I close the issue. Please reopen it if it is relevant with latest versions of focus-graph.

**Comment by tadamK** [comment]
![image](https://cloud.githubusercontent.com/assets/14274196/20064365/ba77a2c0-a50a-11e6-990d-93b31ca6450c.png)
