### ISSUE TITLE
[FieldFor] Formatter/Unformatter not used when defined in domain

### ISSUE THREAD

**Issue by tadamK** [get-focus/focus-graph#148]
Hello,

When I use a formatter or an unformatter in a domain, it is not used for the associated fields displayed with a fieldFor.

My domain :
```
export default {
    type: 'text',
    unformatter: (data) => {
        return data ? data.toUpperCase() : data;
    },
    validator: [{
        type: 'string',
        options: {
            maxLength: 2
        }
    }]
};
```
This should display my string in upper case.

However, when I declare the unformatter directly in the props of the fieldFor, it works.

**"focus-components": "3.0.0-rc46"
"focus-graph": "3.0.0-beta4"**

**Comment by GuenoleK** [comment]
Hello @tadamK , 

as i can see, i think the actual version dosen't support an `unformatter` attribute. By the moment, the `formatter` attribute is the only supported.
> source : https://github.com/get-focus/focus-graph/blob/master/src/middlewares/validations.js#L296

I've tested with the formatter attribute and it works well by my side.

**Comment by tadamK** [comment]
Indeed, the formatter function is called and the formatted value is in upper case.

However, the value sent to the server is the value not formatted. The value displayed in edit mode is not formatted either.

**Comment by GuenoleK** [comment]
Yes, as we have see together, the value displayed in edit mode is the rawInputValue, i thinks the rawInputValue is also sent to the server.
We gotta see with @TomGallon what to do for the possible different cases. Thanks @tadamK for the report
