### ISSUE TITLE
[SnackBar] Center the snackbar

### ISSUE THREAD

**Issue by rodolpheV** [get-focus/focus-graph#153]
# Current Behaviour
The Snackbar is not properly centered. It is the left border of the snackbar that is centered:
![snackbarnotcentered](https://cloud.githubusercontent.com/assets/15649023/20622286/6818db4c-b302-11e6-942f-47cac171185c.PNG)

# Expected Behaviour
Center the SnackBar:
![snackbarcentered](https://cloud.githubusercontent.com/assets/15649023/20622367/d0e9d1e4-b302-11e6-88e2-4311b81c7157.PNG)

# Analysis
By default, the mdl snackbar is centered thanks to: 'transform: translate(-50%,0);'.
But this translate is overridden by the class: animated slideInUp.
A solution would be to add a container within the mdl snackbar and give it the property: 'transform: translate(-50%,0);'.

**Comment by GuenoleK** [comment]
Thanks, this issue have to be reported in focus components @rodolpheV
