### ISSUE TITLE
Global error and focus form 

### ISSUE THREAD

**Issue by jordanbenzacken** [get-focus/focus-graph#156]
With a focus form V3, after a save, when the server return a globalError like this : 

res.status(422).send({globalErrors: ["code already assigned"]});

The behaviour is ok (red toast appears) but the form stay at [saving:true] because redux didn't dispatch on the node (which is logical)

What wood be the good way to implement this ?

**Comment by TomGallon** [comment]
@jordanbenzacken for me the saving value should be dispatched to false after an error
