### ISSUE TITLE
[MasterData] Make master data store easier to access.

### ISSUE THREAD

**Issue by rodolpheV** [get-focus/focus-graph#163]
In a component, when I use connectToMasterData from focus-graph/behaviours/master-data, I expect the corresponding reference list to be easily accessible from this component.
Currently, connectToMasterData just give a load method. I would expect it to give access to the corresponding part of the store too.

For the sake of explanation on what I wanted, here is a helper I wrote myself that does what I needed:
```
export const selectMasterData = arrayOfNames => (state ={}) => {
    const {masterData} = state;

    let hashTable = {};
    for (let name of arrayOfNames) {
        const dataSet = _.find(masterData, m => m.name = name);
        if (dataSet) {
            hashTable[name] = dataSet.value;
        } else {
            console.log('Name ' + name + ' did not exist in the master data store.');
        }
    }

    return {masterDataList: hashTable};
} 
```

its call:
`const exportedComponent = connectToState(selectMasterData(['role']))(Component)`

and its use in my component:
```
const roleList = this.props.masterDataList.role;
const adminRoleId = roleList.find(r => r.code === "ADMIN").id;
if (user.roleId === adminRoleId) console.log('I am admin.')
```

What I expect is to directly do:
`const exportedComponent = connectToMasterData(['role'])(Component)`
And not have to write myself a helper.

**Comment by Ephrame** [comment]
Yes, we can do that ! 
But, as we have seen with @tadamK, you can't do a find like this ( with a single "=" ) on an object. If you do that, you update the real state.

**Comment by tadamK** [comment]
#YOLO

**Comment by rodolpheV** [comment]
My bad I missed some equals, most common Js beginner error. Anyway, thanks for the feedback.

**Comment by Ephrame** [comment]
I have resolved this issue as following : 
```
 export const selectreferenceList = nameListRef => (state ={}) => {
   const {masterData} = state;
   const listRef = masterData.reduce((acc, element) => {
     if(nameListRef.indexOf(element.name)!== -1) acc.push(element)
     return acc;
   },[])
   return {referenceList: listRef}
 }
```
