### ISSUE TITLE
[MasterData] is not loaded to display a field value in consult mode

### ISSUE THREAD

**Issue by TomGallon** [get-focus/focus-graph#51]
In consult mode, my select field is displayed without using the master data gender :

![image](https://cloud.githubusercontent.com/assets/5349745/17439740/c2143a6e-5b29-11e6-810f-48afdbb746e6.png)

In edit mode, the master data list gender is well used : 

![image](https://cloud.githubusercontent.com/assets/5349745/17439783/f7433a78-5b29-11e6-9b51-30d19d0af5e2.png)

**Comment by pierr** [comment]
The problem is not what you says (I think).
It may be in the `DisplayComponent` which does not handle the `code` part.

**Comment by pierr** [comment]
- In the `FieldFor` https://github.com/get-focus/focus-graph/blob/master/src/components/field.js#L12

**Comment by pierr** [comment]
- In the `DisplayComponent` https://github.com/get-focus/focus-graph/blob/master/src/components/display.js

**Comment by pierr** [comment]
@TomGallon Maybe you can check your `props` to see if the `MasterData` informations are present.

**Comment by Ephrame** [comment]
#75
