### ISSUE TITLE
[IMPORTANT] Form: separate state shape from entity shape

### ISSUE THREAD

**Issue by TomGallon** [get-focus/focus-graph#52]
![image](https://cloud.githubusercontent.com/assets/5349745/17440074/558126d0-5b2b-11e6-8971-bd2d0433ede0.png)

Same question for reducers

Data put in the state has the property name:

![image](https://cloud.githubusercontent.com/assets/5349745/17440386/a85be222-5b2c-11e6-88a7-014807359ffa.png)

What do i do if i want the object having a different name in my state ?

in this case, i have only one object person in my store ? Is this a problem ?

![image](https://cloud.githubusercontent.com/assets/5349745/17440741/2537678e-5b2e-11e6-846e-dc43a0db5d05.png)

**Comment by pierr** [comment]
@TomGallon Find a better name :monkey_face:

**Comment by pierr** [comment]
https://github.com/get-focus/focus-graph/blob/master/src/behaviours/form.js#L145

**Comment by Ephrame** [comment]
https://github.com/get-focus/focus-graph/pull/65
