### ISSUE TITLE
Violent Error using fieldFor from connectToFieldHelpers whitout using connectToForm

### ISSUE THREAD

**Issue by TomGallon** [get-focus/focus-graph#55]
```javascript
export default compose(
    connectToStore(
        selectData('person'), // same thing : (state) => state.dataset.person
    ),
    connectToMetadata(['person']),
    connectToFieldHelpers()
)(PersonHeaderExpanded);
```

--> i did not have defined a connectToForm. When i use `fieldFor`, an error appears saying the entityPathArray is not defined.

==> it should have been great to have a error message saying you cannot use a fieldFor without defining a connectToForm. But i not sure it is possible.

**Comment by pierr** [comment]
I'm not sure what to do about this 
There is already a check inside the props which is cleaner.
You are not forced to use the `connectToForm` you could provide the `props` with another way.

But maybe we could add a hint inside the error message.

**Comment by Ephrame** [comment]
Duplicate issue : https://github.com/get-focus/focus-graph/issues/73
