### ISSUE TITLE
Going back to a form shows the old values

### ISSUE THREAD

**Issue by tadamK** [get-focus/focus-graph#60]
Hello,

I have the same "problem" with focus-graph as with focus-core/components.

Ex. with a popin : 
I click on the **add** button to create a data : it opens the popin with the fields blank, OK
I click on a **detail**, it opens the popin with the fields filled with the data, OK
I click again on the **add** button, it opens the popin with the fields filled with the old data, KO

Also, when we click again on another detail, the old data appears during a few ms, then it is replaced by the new data.

To get round of it in focus-components, we used to dispatch a "void" data in the specific store when closing the popin. Is there any other fix in focus-graph ?

**Comment by Ephrame** [comment]
@TomGallon and @pierr  We have to do implement the array of values no ?

**Comment by Ephrame** [comment]
#95
