### ISSUE TITLE
State shape

### ISSUE THREAD

**Issue by pierr** [get-focus/focus-graph#7]
We need to define the state shape. 
Here is my proposal, feel free to add your suggestions : propositions. 
```javascript
{
  currentUser:{profile, roles, culture} ,// all the user related information
  routes, // all the router part of the state, see redux react router
  data, // documents ? all the informations from the entities of the app, all the document tree data , we have to find a better name it is not a good one
  layout: {headerCenter, headerExtended, barContentRight, barContentLeft, isExpended}, // all the layout components
  application, // all the application related informations,
  extensions: { commentCenter, notificationCenter, documentCenter, ...},  // all the extensions informations
  dx: {errorCenter, stateCenter} // all dx related infotmations, maybe it should be called devTools
  analytics, // all analytics related informations
  logs // all the application logs
}
```

**Comment by pierr** [comment]
@Tommass @Bernardstanislas It would be great to have your opinion on that!

**Comment by Bernardstanislas** [comment]
`data` seems a bit... too general. Maybe `dataset` ? Or `entityStore` ? I don't know.
Plus, `dx` is too function-oriented. I'd rather call it `centers`
For the rest, it's all cool, except maybe for `currentUser` that I would better see as `user`

**Comment by pierr** [comment]
@Bernardstanislas 
- I find `dataset` good
- For `dx` i agree but `centers` is a bit confusing with the `extensions` node, the idea of this node is to be removed when `PRODUCTION` mode is on. Maybe `devTools`.
- `user` is too general but it's my opinion it can be fine

**Comment by pierr** [comment]
`customData` for all project specific reducers.
