### ISSUE TITLE
[Autocomplete] DidMount at every render

### ISSUE THREAD

**Issue by tadamK** [get-focus/focus-graph#91]
Hello,

I have an autocomplete field in my form. Every time I type on another field (text for instance) there's a render of the form.

The problem is that the autocomplete field mounts every time and it causes a call to the server (with the code resolver).

**Comment by Ephrame** [comment]
#95

**Comment by tadamK** [comment]
Can you reopen it ? It's not fixed for me.

**Comment by tadamK** [comment]
Ok when the inputComponent is a component and not a pure fonction.
